blueprint:
  name: Motion Room Presence
  description: activate a presence boolean with a motion sensor
  domain: automation
  input:
    motion_sensor:
      name: Motion Sensor
      description: This sensor will be used.
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
    presence_boolean:
      name: Presence Boolean
      description: The presence input boolean to be activated/deactivated.
      selector:
        entity:
          domain: input_boolean

trigger:
  - platform: state
    entity_id: !input motion_sensor

action:
  - service: >
      {% if trigger.to_state.state == "on" %}
        input_boolean.turn_on
      {% else %}
        input_boolean.turn_off
      {% endif %}
    entity_id: !input presence_boolean