# Example configuration.yaml entry

- platform: ping
  host: 192.168.4.43
  name: phone_presence
  count: 2
  scan_interval: 5

- platform: ping
  host: 192.168.4.32
  name: macbook_presence
  count: 2
  scan_interval: 5

- platform: template
  sensors: !include_dir_merge_named binary_sensors/
