
- platform: random
  name: Random Sensor
  minimum: 1
  maximum: 5

- platform: systemmonitor
  resources:
    - type: processor_use
    - type: disk_use_percent
      arg: "/"
    - type: disk_free
      arg: "/"
    - type: memory_use_percent
    - type: network_in
      arg: eth0
    - type: throughput_network_in
      arg: eth0
    - type: network_out
      arg: eth0
    - type: throughput_network_out
      arg: eth0
    - type: processor_temperature
    - type: last_boot

- platform: template
  sensors: !include_dir_merge_named sensors/

- platform: statistics
  name: Weekly Living Room Air Freshness
  entity_id: binary_sensor.is_living_room_air_fresh
  state_characteristic: average_step
  max_age:
    days: 7
  precision: 2

- platform: statistics
  name: Weekly Bed Room Air Freshness
  entity_id: binary_sensor.is_bed_room_air_fresh
  state_characteristic: average_step
  max_age:
    days: 7
  precision: 2

- platform: statistics
  name: Weekly Bath Room Air Freshness
  entity_id: binary_sensor.is_bath_room_air_fresh
  state_characteristic: average_step
  max_age:
    days: 7
  precision: 2

- platform: statistics
  name: Weekly Office Air Freshness
  entity_id: binary_sensor.is_office_air_fresh
  state_characteristic: average_step
  max_age:
    days: 7
  precision: 2

- platform: statistics
  name: Weekly Home Presence
  entity_id: binary_sensor.home_presence
  state_characteristic: average_step
  max_age:
    days: 7
  precision: 2

- platform: statistics
  name: Weekly Vacuum Count
  entity_id: binary_sensor.roborock_s7_cleaning
  state_characteristic: count_on
  max_age:
    days: 7
  precision: 2

- platform: statistics
  name: Weekly time Lorenzo is at home
  entity_id: binary_sensor.is_lorenzo_home
  state_characteristic: average_step
  max_age:
    days: 7
  precision: 2

- platform: statistics
  name: Weekly time in bed room
  entity_id: binary_sensor.bed_room_presence
  state_characteristic: average_step
  max_age:
    days: 7
  precision: 2
- platform: statistics
  name: Weekly time in bath room
  entity_id: binary_sensor.bath_room_presence
  state_characteristic: average_step
  max_age:
    days: 7
  precision: 2
- platform: statistics
  name: Weekly time in office
  entity_id: binary_sensor.office_presence
  state_characteristic: average_step
  max_age:
    days: 7
  precision: 2
- platform: statistics
  name: Weekly time in hallway
  entity_id: binary_sensor.hallway_presence
  state_characteristic: average_step
  max_age:
    days: 7
  precision: 2
- platform: statistics
  name: Weekly time in living room
  entity_id: binary_sensor.living_room_presence
  state_characteristic: average_step
  max_age:
    days: 7
  precision: 2
- platform: statistics
  name: Weekly time in dining room
  entity_id: binary_sensor.dining_room_presence
  state_characteristic: average_step
  max_age:
    days: 7
  precision: 2
- platform: statistics
  name: Weekly time in bar
  entity_id: binary_sensor.bar_presence
  state_characteristic: average_step
  max_age:
    days: 7
  precision: 2
- platform: statistics
  name: Weekly time in entrance
  entity_id: binary_sensor.entrance_presence
  state_characteristic: average_step
  max_age:
    days: 7
  precision: 2
- platform: statistics
  name: Weekly time in kitchen
  entity_id: binary_sensor.kitchen_presence
  state_characteristic: average_step
  max_age:
    days: 7
  precision: 2
- platform: statistics
  name: Weekly time in toilet
  entity_id: binary_sensor.toilet_presence
  state_characteristic: average_step
  max_age:
    days: 7
  precision: 2
- platform: statistics
  name: Weekly light in living room
  entity_id: sensor.living_room_light
  state_characteristic: percentile
  percentile: 90
  max_age:
    days: 7
  precision: 2
- platform: statistics
  name: Daily light in living room
  entity_id: sensor.living_room_light
  state_characteristic: percentile
  percentile: 90
  max_age:
    days: 1
  precision: 2