# Example configuration.yaml entry

- platform: template
  sensors:
    sun_up:
      friendly_name: "Sun is up"
      value_template: >-
        {{ state_attr('sun.sun', 'elevation')|float > 0 }}
    kitchen_speaker_in_group:
      friendly_name: "Kitchen speaker is in group"
      value_template: >-
        {% if state_attr('media_player.kitchen_speaker', 'sonos_group')|length > 1 %}
          on
        {% else %}
         off
        {% endif %}
      icon_template: >-
        {% if is_state("binary_sensor.kitchen_speaker_in_group", "on") %}
          mdi:speaker-multiple
        {% else %}
          mdi:speaker
        {% endif %}

    bath_room_speaker_in_group:
      friendly_name: "Bathroom speaker is in group"
      value_template: >-
        {% if state_attr('media_player.bath_room_speaker', 'sonos_group')|length > 1 %}
          on
        {% else %}
         off
        {% endif %}
      icon_template: >-
        {% if is_state("binary_sensor.bath_room_speaker_in_group", "on") %}
          mdi:speaker-multiple
        {% else %}
          mdi:speaker
        {% endif %}

    bed_room_speaker_in_group:
      friendly_name: "Bedroom speaker is in group"
      value_template: >-
        {% if state_attr('media_player.bed_room_speaker', 'sonos_group')|length > 1 %}
          on
        {% else %}
         off
        {% endif %}
      icon_template: >-
        {% if is_state("binary_sensor.bed_room_speaker_in_group", "on") %}
          mdi:speaker-multiple
        {% else %}
          mdi:speaker
        {% endif %}

    living_room_speaker_in_group:
      friendly_name: "Bedroom speaker is in group"
      value_template: >-
        {% if state_attr('media_player.living_room_speaker', 'sonos_group')|length > 1 %}
          on
        {% else %}
         off
        {% endif %}
      icon_template: >-
        {% if is_state("binary_sensor.living_room_speaker_in_group", "on") %}
          mdi:speaker-multiple
        {% else %}
          mdi:speaker
        {% endif %}