
- platform: random
  name: Random Sensor
  minimum: 1
  maximum: 5

- platform: systemmonitor
  resources:
    - type: processor_use
    - type: disk_use_percent
      arg: "/"
    - type: disk_free
      arg: "/"
    - type: memory_use_percent
    - type: network_in
      arg: eth0
    - type: throughput_network_in
      arg: eth0
    - type: network_out
      arg: eth0
    - type: throughput_network_out
      arg: eth0
    - type: processor_temperature
    - type: last_boot

- platform: command_line
  name: CPU Temp
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
  value_template: '{{ value | multiply(0.001) | round(2)  }}'

- platform: filesize
  file_paths:
    - /config/home-assistant_v2.db

- platform: template
  sensors:
    living_room_temperature_rounded:
      friendly_name: "Living Room Temperature Rounded"
      unit_of_measurement: "°C"
      value_template: >-
        {{
          states('sensor.living_room_temperature')|float|round(1)
        }}
    living_room_air_freshness:
      friendly_name: "Living Room Air Freshness"
      unit_of_measurement: "h"
      value_template: >-
        {{
          ((now().timestamp() - states.binary_sensor.living_room_open_window.last_changed.timestamp())/3600)|int
        }}

    bed_room_temperature_rounded:
      friendly_name: "Bed Room Temperature Rounded"
      unit_of_measurement: "°C"
      value_template: >-
        {{
          states('sensor.bed_room_temperature')|float|round(1)
        }}
    bed_room_air_freshness:
      friendly_name: "Bed Room Air Freshness"
      unit_of_measurement: "h"
      value_template: >-
        {{
          ((now().timestamp() - states.binary_sensor.bed_room_open_window.last_changed.timestamp())/3600)|int
        }}

    bath_room_temperature_rounded:
      friendly_name: "Bath Room Temperature Rounded"
      unit_of_measurement: "°C"
      value_template: >-
        {{
          states('sensor.bath_room_temperature')|float|round(1)
        }}
    bath_room_air_freshness:
      friendly_name: "Bath Room Air Freshness"
      unit_of_measurement: "h"
      value_template: >-
        {{
          ((now().timestamp() - states.binary_sensor.bath_room_open_window.last_changed.timestamp())/3600)|int
        }}

    office_temperature_rounded:
      friendly_name: "Office Temperature Rounded"
      unit_of_measurement: "°C"
      value_template: >-
        {{
          states('sensor.office_temperature')|float|round(1)
        }}
    office_air_freshness:
      friendly_name: "office Air Freshness"
      unit_of_measurement: "h"
      value_template: >-
        {{
        ((now().timestamp() - states.binary_sensor.office_open_window.last_changed.timestamp())/3600)|int
        }}
