# Example configuration.yaml entry

- platform: template
  sensors:
    sun_up:
      friendly_name: "Sun is up"
      value_template: >-
        {{ state_attr('sun.sun', 'elevation')|float > 0 }}
    kitchen_speaker_in_group:
      friendly_name: "Kitchen speaker is in group"
      value_template: >-
        {% if state_attr('media_player.kitchen_speaker', 'sonos_group')|length > 1 %}
          on
        {% else %}
         off
        {% endif %}
      icon_template: >-
        {% if is_state("binary_sensor.kitchen_speaker_in_group", "on") %}
          mdi:speaker-multiple
        {% else %}
          mdi:speaker
        {% endif %}

    bath_room_speaker_in_group:
      friendly_name: "Bathroom speaker is in group"
      value_template: >-
        {% if state_attr('media_player.bath_room_speaker', 'sonos_group')|length > 1 %}
          on
        {% else %}
         off
        {% endif %}
      icon_template: >-
        {% if is_state("binary_sensor.bath_room_speaker_in_group", "on") %}
          mdi:speaker-multiple
        {% else %}
          mdi:speaker
        {% endif %}

    office_speaker_in_group:
      friendly_name: "Office speaker is in group"
      value_template: >-
        {% if state_attr('media_player.office_speaker', 'sonos_group')|length > 1 %}
          on
        {% else %}
         off
        {% endif %}
      icon_template: >-
        {% if is_state("binary_sensor.office_speaker_in_group", "on") %}
          mdi:speaker-multiple
        {% else %}
          mdi:speaker
        {% endif %}

    living_room_speaker_in_group:
      friendly_name: "Bedroom speaker is in group"
      value_template: >-
        {% if state_attr('media_player.living_room_speaker', 'sonos_group')|length > 1 %}
          on
        {% else %}
         off
        {% endif %}
      icon_template: >-
        {% if is_state("binary_sensor.living_room_speaker_in_group", "on") %}
          mdi:speaker-multiple
        {% else %}
          mdi:speaker
        {% endif %}

    presence_in_multiple_rooms:
      friendly_name: "Presence Booleans are true in multiple rooms"
      value_template: >-
        {{
           is_state('input_boolean.bed_room_presence', 'on')|int +
           is_state('input_boolean.kitchen_presence', 'on')|int +
           is_state('input_boolean.toilet_presence', 'on')|int +
           is_state('input_boolean.living_room_presence', 'on')|int +
           is_state('input_boolean.hallway_presence', 'on')|int +
           is_state('input_boolean.bath_room_presence', 'on')|int +
           is_state('input_boolean.office_presence', 'on')|int > 1
        }}
      icon_template: mdi:account-check