- platform: group
  name: Wohnzimmer Deckenlampe
  entities:
    - light.living_room_head_lamp_1
    - light.living_room_head_lamp_2
    - light.living_room_head_lamp_3
    - light.living_room_head_lamp_4
    - light.living_room_head_lamp_5