
- platform: random
  name: Random Sensor
  minimum: 1
  maximum: 5

- platform: systemmonitor
  resources:
    - type: processor_use
    - type: disk_use_percent
      arg: "/"
    - type: disk_free
      arg: "/"
    - type: memory_use_percent
    - type: network_in
      arg: eth0
    - type: throughput_network_in
      arg: eth0
    - type: network_out
      arg: eth0
    - type: throughput_network_out
      arg: eth0
    - type: processor_temperature
    - type: last_boot

- platform: template
  sensors: !include_dir_merge_named sensors/

- platform: statistics
  name: Weekly Living Room Air Freshness
  entity_id: binary_sensor.is_living_room_air_fresh
  state_characteristic: average_step
  max_age:
    days: 7

- platform: statistics
  name: Weekly Bed Room Air Freshness
  entity_id: binary_sensor.is_bed_room_air_fresh
  state_characteristic: average_step
  max_age:
    days: 7

- platform: statistics
  name: Weekly Bath Room Air Freshness
  entity_id: binary_sensor.is_bath_room_air_fresh
  state_characteristic: average_step
  max_age:
    days: 7

- platform: statistics
  name: Weekly Office Air Freshness
  entity_id: binary_sensor.is_office_air_fresh
  state_characteristic: average_step
  max_age:
    days: 7

- platform: statistics
  name: Weekly Home Presence
  entity_id: binary_sensor.home_presence
  state_characteristic: average_step
  max_age:
    days: 7
