blueprint:
  name: Start Presence timer when motion stops
  description: Start Presence timer when motion stops
  domain: automation
  input:
    presence_timer:
      name: Presence Timer
      description: The presence timer that will start
      selector:
        entity:
          domain: timer
    presence_timer_night:
      name: Presence timer night
      description: Timer that stores presence
      selector:
        entity:
          domain: timer
    presence_timer_evening:
      name: Presence timer evening
      description: Timer that stores presence
      selector:
        entity:
          domain: timer
    motion_sensor_active:
      name: Motion Sensor Boolean
      description: Boolean that determines if this motion sensor is active
      selector:
        entity:
          domain: input_boolean
    motion_sensor:
      name: Motion Sensor
      description: This sensor will be used.
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
    presence_boolean:
      name: Presence Boolean
      description: The presence input boolean to be activated/deactivated.
      selector:
        entity:
          domain: input_boolean

trigger:
  - platform: state
    entity_id: !input presence_boolean
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: !input motion_sensor

condition:
  - condition: state
    entity_id: !input motion_sensor_active
    state: 'on'

action:
  - choose:
    - conditions:
        - condition: state
          entity_id: sensor.time_of_day
          state: night
      sequence:
        - service: script.start_presence_timer
          data_template:
            entity: !input presence_timer_night
    - conditions:
        - condition: state
          entity_id: sensor.time_of_day
          state: evening
      sequence:
        - service: script.start_presence_timer
          data_template:
            entity: !input presence_timer_evening
    default:
      - service: script.start_presence_timer
        data_template:
          entity: !input presence_timer
