blueprint:
  name: Vacuum button
  description: ""
  domain: automation
  input:
    room:
      name: Room name
      description: Room name
    passes:
      name: Vacuum passes
      description: Vacuum passes
      default: 1
    speaker:
      name: Speaker to use
      description: Speaker to use
      selector:
        entity:
          domain: media_player
    switch_device_id:
      name: Switch to use
      description: Switch to use
    switch_action_subtype:
      name: Switch to use
      description: Switch to use
      default: ''


variables:
  room: !input room
  speaker: !input speaker
  switch_device_id: !input switch_device_id
  room_name: '{{room.replace("_", " ")}}'


trigger:
  - device_id: !input switch_device_id
    domain: deconz
    platform: device
    type: remote_button_short_press
    subtype: !input switch_action_subtype
  - device_id: !input switch_device_id
    domain: deconz
    platform: device
    type: remote_button_long_press
    subtype: !input switch_action_subtype

condition: []

action:
  - choose:
    - conditions:
        - condition: template
          value_template: '{{trigger.event.data.event == 1002 }}'
      sequence:
        - if:
            - condition: template
              value_template: '{{states("var.vacuum_queue")|from_json|from_json|length > 0 }}'
          then:
            - service: tts.cloud_say
              data:
                entity_id: !input speaker
                message: 'Adding {{room_name}} to the vacuum queue'
                cache: true
          else:
            - service: tts.cloud_say
              data:
                entity_id: !input speaker
                message: 'Sending Henry to the {{room_name}}'
                cache: true
        - service: script.add_to_cleaning_queue
          data_template:
            rooms:
              - '{{ room }}'
            passes: !input passes
    - conditions:
        - condition: template
          value_template: '{{trigger.event.data.event == 1001 }}'
      sequence:
        - service: tts.cloud_say
          data:
            entity_id: !input speaker
            message: Sending Henry home
            cache: true
        - service: script.send_vacuum_to_dock
mode: parallel