blueprint:
  name: Warn about windows being open for too long
  description: ""
  domain: automation
  input:
    room:
      name: Room name
      description: Room name
    tracker:
      name: Tracker boolean
      description: Input boolean to track freshness
      selector:
        entity:
          domain: input_boolean

variables:
  room: !input room

trigger:
  - platform: state
    entity_id: !input tracker
    to: "on"
    for:
      hours: 2

condition:
  - condition: state
    entity_id: input_boolean.warn_windows_open
    state: 'on'

action:
- service: script.send_notification
  data_template:
    message: "The {{ room }} window has been open for 2 hours"
    title: Window open too long
