blueprint:
  name: Warn about windows being open for too long
  description: ""
  domain: automation
  input:
    room:
      name: Room name
      description: Room name
    window:
      name: Window
      description: Window
      selector:
        entity:
          domain: binary_sensor

variables:
  room: !input room

trigger:
  - platform: state
    entity_id: !input window
    to: "on"
    for:
      hours: 2

condition:
  - condition: state
    entity_id: input_boolean.warn_windows_open
    state: 'on'

action:
- service: script.send_air_freshness_notification
  data_template:
    message: "The {{ room }} window has been open for 2 hours"
    title: Window open too long
    link: "{{ '/room-overview/' + room.replace(' ','-') + '-' }}"
