blueprint:
  name: Warn about air freshness using the window
  description: ""
  domain: automation
  input:
    room:
      name: Room name
      description: Room name
    tracker:
      name: Tracker boolean
      description: Input boolean to track freshness
      selector:
        entity:
          domain: binary_sensor

variables:
  room: !input room

trigger:
  - platform: state
    entity_id: !input tracker
    from: "off"
    to: "on"
  - platform: state
    entity_id: !input tracker
    from: "on"
    to: "off"
    for:
      hours: 1

condition:
  - condition: state
    entity_id: input_boolean.warn_air_freshness
    state: "on"

action:
- if:
  - condition: state
    entity_id: !input tracker
    state: "off"
  then:
  - service: script.send_air_freshness_notification
    data_template:
      message: "The {{ room }} needs to be aired."
      title: Air freshness warning
      link: "{{ '/room-overview/' + room.replace(' ','-') + '-' }}"
  else:
  - service: script.send_air_freshness_notification
    data_template:
      message: "The air in the {{ room }} is now fresh"
      title: Air freshness information
      link: "{{ '/room-overview/' + room.replace(' ','-') + '-' }}"
