blueprint:
  name: Window turns off heating when open
  description: ""
  domain: automation
  input:
    window:
      name: Window
      description: Window
      selector:
        entity:
          domain: binary_sensor
    heating:
      name: Heating
      description: Heating
      selector:
        entity:
          domain: climate
    heating_state_field:
      name: Heating Input Text
      description: Heating Input Text
      selector:
        entity:
          domain: input_text

trigger:
  - platform: state
    entity_id: !input window
    from: 'on'
    to: 'off'
    for: '10'
  - platform: state
    entity_id: !input window
    from: 'off'
    to: 'on'
    for: '10'

condition:
  - condition: state
    entity_id: input_boolean.automate_heating
    state: 'on'

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: !input window
            state: 'on'
        sequence:
          - service: script.turn_off_heating
            data:
              heating_state_field: !input heating_state_field
              heating: !input heating
      - conditions:
          - condition: state
            entity_id: !input window
            state: 'off'
        sequence:
          - service: script.turn_on_heating
            data:
              heating_state_field: !input heating_state_field
              heating: !input heating
